version: '3'
services:
  registry:
    build: registry
    ports:
      - "8081:8081"
    environment:
      TZ: "Asia/Shanghai"
  web1:
    build: web1
    ports:
      - "8082:8082"
    environment:
      TZ: "Asia/Shanghai"
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: "Asia/Shanghai"
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    environment:
      TZ: "Asia/Shanghai"
