server:
  port: 8111

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry1:8001/eureka, http://registry2:8002/eureka

#
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  restclient:
#    enabled: true
#zuul:
#  routes:
#    web2:
#      path: /web2/**
#      serviceId: web2
#
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#        thread:
#          timeoutInMilliseconds: 60000

spring.profile