server:
  port: 8083

spring:
  application:
    name: web2

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry1:8001/eureka, http://registry2:8002/eureka
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
#        retryer: feign.Retryer.Default

